# This workflow will build using node when a PR is created

name: Build Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js with NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Setup Pulumi
        uses: docker://pulumi/actions:v2.13.2
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Install dependencies
        run: npm i
      - name: Linting source files
        run: npm run lint
      - name: Building source files
        run: npm run build
      - name: Semantic Release (DryRun)
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
